# Change these first
owner: alejandroosunna # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: staging01
    url: https://staging01.algebraix.com/bin/g/start/default/?x_load=0
  - name: staging02
    url: https://staging02.algebraix.com/bin/g/start/default/?x_load=0
  - name: staging03
    url: https://staging03.algebraix.com/bin/g/start/default/?x_load=0
  - name: staging04
    url: https://staging04.algebraix.com/bin/g/start/default/?x_load=0
  - name: staging05
    url: https://staging05.algebraix.com/bin/g/start/default/?x_load=0
  - name: staging06
    url: https://staging06.algebraix.com/bin/g/start/default/?x_load=0
  - name: staging07
    url: https://staging07.algebraix.com/bin/g/start/default/?x_load=0
  - name: staging08
    url: https://staging08.algebraix.com/bin/g/start/default/?x_load=0
  - name: staging09
    url: https://staging09.algebraix.com/bin/g/start/default/?x_load=0
  - name: staging10
    url: https://staging10.algebraix.com/bin/g/start/default/?x_load=0
  - name: staging11
    url: https://staging11.algebraix.com/bin/g/start/default/?x_load=0
  - name: staging12
    url: https://staging12.algebraix.com/bin/g/start/default/?x_load=0
  - name: staging13
    url: https://staging13.algebraix.com/bin/g/start/default/?x_load=0
  - name: staging14
    url: https://staging14.algebraix.com/bin/g/start/default/?x_load=0
  - name: staging15
    url: https://staging15.algebraix.com/bin/g/start/default/?x_load=0
  - name: staging16
    url: https://staging16.algebraix.com/bin/g/start/default/?x_load=0
    
assignees:
  - alejandroosunna

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
